Move root user check to linux shell script

diff --git a/SparkleShare/sparkleshare.in b/SparkleShare/sparkleshare.in
--- a/SparkleShare/sparkleshare.in
+++ b/SparkleShare/sparkleshare.in
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ $UID -e 0 ]]; then
+  echo "Cannot run as root. Things would go utterly wrong."
+  exit 1
+fi
+
 if [ "$XDG_RUNTIME_DIR" ]; then
   pidfile=${XDG_RUNTIME_DIR}/sparkleshare.pid
 else
